added ssh directory prep

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -138,7 +138,7 @@ pass "Prezto Installed Successfully"
 DEFAULT_SHELL=zsh
 DEFAULT_SHELL_PATH=$(command -v $DEFAULT_SHELL)
 
-say "About to set set default shell to $DEFAULT_SHELL"
+say "Preparing to set set default shell to $DEFAULT_SHELL"
 
 [[ -e $DEFAULT_SHELL_PATH ]] || fail "$DEFAULT_SHELL does not seem to be available...aborting!"
 
@@ -147,6 +147,23 @@ if [[ current_shell == $DEFAULT_SHELL_PATH ]]; then
 else
   chsh -s $DEFAULT_SHELL_PATH  || fail "Unable to set shell to $DEFAULT_SHELL_PATH"
 fi
+
+################################################################################
+# Ensure proper permissions for ssh files and folders.
+################################################################################
+
+SSH_PATH=$HOME/.ssh
+
+say "Preparing $SSH_PATH"
+
+if [[ ! -d $SSH_PATH ]]; then
+  mkdir -p $SSH_PATH || fail "Unable to create directory ($SSH_PATH)...aborting!"
+fi
+
+say "Setting permissions on ($SSH_PATH)"
+
+chmod 700 $SSH_PATH   || fail "command failed: chmod 700 $SSH_PATH"
+chmod 600 $SSH_PATH/* || fail "comamnd failed: chmod 600 $SSH_PATH/*"
 
 ################################################################################
 # fin
