better error handling and idempotency for shell changing

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -72,6 +72,15 @@ linkable_dotfiles () {
     ! -name '.git*'
 }
 
+#
+# report own current shell
+#
+
+current_shell () {
+  # OSX specific (todo: make this less osx specific)
+  dscl localhost -read /Local/Default/Users/$USER shell | awk '{ print $NF }'
+}
+
 ################################################################################
 # clone dotfiles repo
 ################################################################################
@@ -126,24 +135,22 @@ pass "Prezto Installed Successfully"
 # set default shell to "Zsh"
 ################################################################################
 
-# check current shell on OSX via: dscl localhost -read /Local/Default/Users/$USER shell | awk '{ print $NF }'
-# todo: make this idempotent
-# todo: more granular error handling
+TARGET_SHELL=zsh
+TARGET_SHELL_PATH=$(command -v $TARGET_SHELL)
 
-function set_shell() {
-  local target_shell=$(command -v $1)
+say "About to set set default shell to $TARGET_SHELL"
 
-  chsh -s $target_shell 2>/dev/null
+[[ -e $TARGET_SHELL_PATH ]] || fail "$TARGET_SHELL does not seem to be available...aborting!"
 
-  return $?
-}
-
-#say "About to set set default shell to zsh"
-#set_shell zsh || fail "Unable to set shell to zsh"
-#pass "Successfully set shell to zsh"
+if [[ current_shell == $TARGET_SHELL_PATH ]]; then
+  pass "Current shell is already set to ($TARGET_SHELL_PATH)...nothing to do!"
+else
+  chsh -s $TARGET_SHELL_PATH  || fail "Unable to set shell to $TARGET_SHELL_PATH"
+fi
 
 ################################################################################
 # fin
 ################################################################################
 
 pass "dotfile installation completed successfully."
+
