Update setup

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -121,7 +121,7 @@ say "Preparing to install Prezto"
 if [[ -d "$HOME/.zprezto" ]]; then
   say "directory: ("$HOME/.zprezto") exists; skipping clone"
 else
-  git clone git clone --recursive https://github.com/sorin-ionescu/prezto.git "$HOME/.zprezto" || fail "unable to clone Prezto"
+  git clone --recursive https://github.com/sorin-ionescu/prezto.git "$HOME/.zprezto" 2>/dev/null || fail "Failed to clone Prezto...aborting!"
 fi
 
 say "Preparing to update Prezto"
